name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project from GitHub
        uses: actions/checkout@v3
      
      - name: Test and build frontend
        run: 'make frontend-build'

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Test and build backend
        run: 'make backend-build'

      - name: Build and tag application image
        shell: bash
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: |
          make build-app-image
          docker tag service-catalog "$DOCKER_HUB_USER"/service-catalog
      
      - name: Logging in to Docker Hub
        shell: bash
        env: 
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: 'docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"'

      - name: Push image to Docker Hub
        shell: bash
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: 'docker push "$DOCKER_HUB_USER"/service-catalog'
