name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project from GitHub
        uses: actions/checkout@v3
      
      - name: Test and build frontend
        run: 'make frontend-build'

      - name: Test and build backend
        run: 'make backend-build'

      - name: Build application image
        run: 'make build-app-image'
